export { connect, type Origin } from './Origin'
export { query } from './query'
export { meta } from './meta'
export type { GenericError } from './Error'
export type { OctetsEntry, WorkflowStep } from './Octets'
export type { Resource } from './Resource'
export type { RequestOptions } from './Agent'
export type { Faulty } from './Octets'
