export { Resource } from './Resource'
export { Method } from './Method'
export { Failure } from './Failure'
export { authenticate, request, use, connect, type Options } from './request'
export { events } from './events'
export type * from './Octets'
